apiVersion: apps/v1
kind: Deployment
metadata:
  name: oklab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oklab
  template:
    metadata:
      labels:
        app: oklab
    spec:
      containers:
      - image: okteto.dev/oklab:latest
        name: somelse
        ports:
        - containerPort: 8080
